#define  MNU_PRINT         0
#define  MNU_PRINTER_SETUP 1
#define  MNU_EXIT          3

#define  MNU_MODEM         0
#define  MNU_SUBSCRIBER    1
#define  MNU_SERVICE       2
#define  MNU_GROUP         3
#define  MNU_PREDEFINED    4

#define  MNU_SETTINGS      0
#define  MNU_LOG           1

#define  MNU_HELP          0
#define  MNU_ABOUT         1

#define  MNU_SAVE          0
#define  MNU_DELETE        1
#define  MNU_CLEAR         2
